### ISSUE TITLE
Room can exist

### ISSUE THREAD

**Issue by louissullivan4** [louissullivan4/chatroom-app#4]

**Comment by CianMcDonald** [comment]
@louissullivan4 This now exists in the program. Would be interested to see you thoughts on the tests I wrote or on any other part!

Links to commits:
[Tests](1c93a3a8bc902cb68a87daecff3f0193c30bbed2)
[Code](417f0aed57b0b3c3d511de0aada317d6f16f8cba)

**Comment by CianMcDonald** [comment]
Finished.
