### ISSUE TITLE
User can be updated or deleted (created added to this issue)

### ISSUE THREAD

**Issue by louissullivan4** [louissullivan4/chatroom-app#6]

**Comment by louissullivan4** [comment]
Cian to review the design of this functionality. 
- When creating or updating an account a JSON is sent with the Account information.
- The json string values needed be converted to Date (dob) and Locale (country). This requires the indivual parsing of each value.
- Both the create and update calls need this functionality so a "newAccountDetails" method was created and is called when an Account is updated or created. 
- Update needs to check if the user already exists and so it requires a second API call (do not combine create and update).

Link to commit:
(https://github.com/louissullivan4/chatroom-app/commit/457c561155023d976acbd19106f22dd19486b175)

**Comment by louissullivan4** [comment]
Also I added API calls to a readme and to a folder called docs (https://github.com/louissullivan4/chatroom-app/tree/1df055fb37086fe568212df8ca5302ed0cb6d7c1/demo/demo/src/test/java/com/example/demo/doc) for ease of use

**Comment by CianMcDonald** [comment]
Looking good Louis sir. We can run code coverage anyway to see what we haven't tested :)
